# The GPS start time for ER8
START = 1123858817
# The GPS end time ER8/O1 (Sep 28, 2015 23:59:59 UTC)
STOP =  1127520016

# Injections
DCHIRP_DISTR = uniform
I_DISTR = uniform
L_DISTR = random
TIME_INTERVAL = 25
TIME_STEP = 100
FLOWER = 25
MIN_DISTANCE = 2000
MAX_DISTANCE = 250000

# BNS INJECTIONS
BNS_MASS_DISTR = componentMass
BNS_MIN_MASS1 = 1.0
BNS_MAX_MASS1 = 3.0
BNS_MIN_MASS2 = 1.0
BNS_MAX_MASS2 = 3.0
BNS_MIN_MTOTAL = 2.0
BNS_MAX_MTOTAL = 6.0
BNS_MIN_SPIN1 = 0.0
BNS_MAX_SPIN1 = 0.4
BNS_MIN_SPIN2 = 0.0
BNS_MAX_SPIN2 = 0.4

# NSBH LOW MASS INJECTIONS
NSBHLM_MASS_DISTR = componentMass
NSBHLM_MIN_MASS1 = 2.0
NSBHLM_MAX_MASS1 = 16.0
NSBHLM_MIN_MASS2 = 1.0
NSBHLM_MAX_MASS2 = 3.0
NSBHLM_MIN_MTOTAL = 3.0
NSBHLM_MAX_MTOTAL = 19.0
NSBHLM_MIN_SPIN1 = 0.0
NSBHLM_MAX_SPIN1 = 0.99
NSBHLM_MIN_SPIN2 = 0.0
NSBHLM_MAX_SPIN2 = 0.4

# NSBH HIGH MASS INJECTIONS
NSBHHM_MASS_DISTR = componentMass
NSBHHM_MIN_MASS1 = 16.0
NSBHHM_MAX_MASS1 = 97.0
NSBHHM_MIN_MASS2 = 1.0
NSBHHM_MAX_MASS2 = 3.0
NSBHHM_MIN_MTOTAL = 17.0
NSBHHM_MAX_MTOTAL = 100.0
NSBHHM_MIN_SPIN1 = 0.0
NSBHHM_MAX_SPIN1 = 0.99
NSBHHM_MIN_SPIN2 = 0.0
NSBHHM_MAX_SPIN2 = 0.4

# BBH INJECTIONS
BBH_MASS_DISTR = totalMass
BBH_MIN_MASS1 = 2.0
BBH_MAX_MASS1 = 97.0
BBH_MIN_MASS2 = 2.0
BBH_MAX_MASS2 = 97.0
BBH_MIN_MTOTAL = 4.0
BBH_MAX_MTOTAL = 100.0
BBH_MIN_SPIN1 = 0.0
BBH_MAX_SPIN1 = 0.99
BBH_MIN_SPIN2 = 0.0
BBH_MAX_SPIN2 = 0.99

all : injections

injections :
	# BNS INJECTIONS: seeds 45671, 45672, 45673
	# Waveform: SpinTaylorT2threePointFivePN
	lalapps_inspinj --min-mass1 ${BNS_MIN_MASS1} --max-mass1 ${BNS_MAX_MASS1} --min-mass2 ${BNS_MIN_MASS2} --max-mass2 ${BNS_MAX_MASS2} --min-mtotal ${BNS_MIN_MTOTAL} --max-mtotal ${BNS_MAX_MTOTAL} --m-distr ${BNS_MASS_DISTR} --enable-spin --min-spin1 ${BNS_MIN_SPIN1} --max-spin1 ${BNS_MAX_SPIN1} --min-spin2 ${BNS_MIN_SPIN2} --max-spin2 ${BNS_MAX_SPIN2} --gps-start-time ${START} --gps-end-time ${STOP} --dchirp-distr ${DCHIRP_DISTR} --min-distance ${MIN_DISTANCE} --max-distance ${MAX_DISTANCE} --l-distr ${L_DISTR} --i-distr ${I_DISTR} --f-lower ${FLOWER} --time-step ${TIME_STEP} --time-interval ${TIME_INTERVAL} --waveform SpinTaylorT2threePointFivePN --taper-injection startend --seed 45671 --user-tag BNS1
	lalapps_inspinj --min-mass1 ${BNS_MIN_MASS1} --max-mass1 ${BNS_MAX_MASS1} --min-mass2 ${BNS_MIN_MASS2} --max-mass2 ${BNS_MAX_MASS2} --min-mtotal ${BNS_MIN_MTOTAL} --max-mtotal ${BNS_MAX_MTOTAL} --m-distr ${BNS_MASS_DISTR} --enable-spin --min-spin1 ${BNS_MIN_SPIN1} --max-spin1 ${BNS_MAX_SPIN1} --min-spin2 ${BNS_MIN_SPIN2} --max-spin2 ${BNS_MAX_SPIN2} --gps-start-time ${START} --gps-end-time ${STOP} --dchirp-distr ${DCHIRP_DISTR} --min-distance ${MIN_DISTANCE} --max-distance ${MAX_DISTANCE} --l-distr ${L_DISTR} --i-distr ${I_DISTR} --f-lower ${FLOWER} --time-step ${TIME_STEP} --time-interval ${TIME_INTERVAL} --waveform SpinTaylorT2threePointFivePN --taper-injection startend --seed 45672 --user-tag BNS2
	lalapps_inspinj --min-mass1 ${BNS_MIN_MASS1} --max-mass1 ${BNS_MAX_MASS1} --min-mass2 ${BNS_MIN_MASS2} --max-mass2 ${BNS_MAX_MASS2} --min-mtotal ${BNS_MIN_MTOTAL} --max-mtotal ${BNS_MAX_MTOTAL} --m-distr ${BNS_MASS_DISTR} --enable-spin --min-spin1 ${BNS_MIN_SPIN1} --max-spin1 ${BNS_MAX_SPIN1} --min-spin2 ${BNS_MIN_SPIN2} --max-spin2 ${BNS_MAX_SPIN2} --gps-start-time ${START} --gps-end-time ${STOP} --dchirp-distr ${DCHIRP_DISTR} --min-distance ${MIN_DISTANCE} --max-distance ${MAX_DISTANCE} --l-distr ${L_DISTR} --i-distr ${I_DISTR} --f-lower ${FLOWER} --time-step ${TIME_STEP} --time-interval ${TIME_INTERVAL} --waveform SpinTaylorT2threePointFivePN --taper-injection startend --seed 45673 --user-tag BNS3
	# NSBH LOW MASS INJECTIONS: seeds 56781, 56782, 56783
	# Waveform: SpinTaylorT2threePointFivePN
	lalapps_inspinj --min-mass1 ${NSBHLM_MIN_MASS1} --max-mass1 ${NSBHLM_MAX_MASS1} --min-mass2 ${NSBHLM_MIN_MASS2} --max-mass2 ${NSBHLM_MAX_MASS2} --min-mtotal ${NSBHLM_MIN_MTOTAL} --max-mtotal ${NSBHLM_MAX_MTOTAL} --m-distr ${NSBHLM_MASS_DISTR} --enable-spin --min-spin1 ${NSBHLM_MIN_SPIN1} --max-spin1 ${NSBHLM_MAX_SPIN1} --min-spin2 ${NSBHLM_MIN_SPIN2} --max-spin2 ${NSBHLM_MAX_SPIN2} --gps-start-time ${START} --gps-end-time ${STOP} --dchirp-distr ${DCHIRP_DISTR} --min-distance ${MIN_DISTANCE} --max-distance ${MAX_DISTANCE} --l-distr ${L_DISTR} --i-distr ${I_DISTR} --f-lower ${FLOWER} --time-step ${TIME_STEP} --time-interval ${TIME_INTERVAL} --waveform SpinTaylorT2threePointFivePN --taper-injection startend --seed 56781 --user-tag NSBHLM1
	lalapps_inspinj --min-mass1 ${NSBHLM_MIN_MASS1} --max-mass1 ${NSBHLM_MAX_MASS1} --min-mass2 ${NSBHLM_MIN_MASS2} --max-mass2 ${NSBHLM_MAX_MASS2} --min-mtotal ${NSBHLM_MIN_MTOTAL} --max-mtotal ${NSBHLM_MAX_MTOTAL} --m-distr ${NSBHLM_MASS_DISTR} --enable-spin --min-spin1 ${NSBHLM_MIN_SPIN1} --max-spin1 ${NSBHLM_MAX_SPIN1} --min-spin2 ${NSBHLM_MIN_SPIN2} --max-spin2 ${NSBHLM_MAX_SPIN2} --gps-start-time ${START} --gps-end-time ${STOP} --dchirp-distr ${DCHIRP_DISTR} --min-distance ${MIN_DISTANCE} --max-distance ${MAX_DISTANCE} --l-distr ${L_DISTR} --i-distr ${I_DISTR} --f-lower ${FLOWER} --time-step ${TIME_STEP} --time-interval ${TIME_INTERVAL} --waveform SpinTaylorT2threePointFivePN --taper-injection startend --seed 56782 --user-tag NSBHLM2
	lalapps_inspinj --min-mass1 ${NSBHLM_MIN_MASS1} --max-mass1 ${NSBHLM_MAX_MASS1} --min-mass2 ${NSBHLM_MIN_MASS2} --max-mass2 ${NSBHLM_MAX_MASS2} --min-mtotal ${NSBHLM_MIN_MTOTAL} --max-mtotal ${NSBHLM_MAX_MTOTAL} --m-distr ${NSBHLM_MASS_DISTR} --enable-spin --min-spin1 ${NSBHLM_MIN_SPIN1} --max-spin1 ${NSBHLM_MAX_SPIN1} --min-spin2 ${NSBHLM_MIN_SPIN2} --max-spin2 ${NSBHLM_MAX_SPIN2} --gps-start-time ${START} --gps-end-time ${STOP} --dchirp-distr ${DCHIRP_DISTR} --min-distance ${MIN_DISTANCE} --max-distance ${MAX_DISTANCE} --l-distr ${L_DISTR} --i-distr ${I_DISTR} --f-lower ${FLOWER} --time-step ${TIME_STEP} --time-interval ${TIME_INTERVAL} --waveform SpinTaylorT2threePointFivePN --taper-injection startend --seed 56783 --user-tag NSBHLM3
	# NSBH LOW MASS INJECTIONS: seeds 56784, 56785, 56786
	# Waveform: SpinTaylorT4threePointFivePN
	lalapps_inspinj --min-mass1 ${NSBHLM_MIN_MASS1} --max-mass1 ${NSBHLM_MAX_MASS1} --min-mass2 ${NSBHLM_MIN_MASS2} --max-mass2 ${NSBHLM_MAX_MASS2} --min-mtotal ${NSBHLM_MIN_MTOTAL} --max-mtotal ${NSBHLM_MAX_MTOTAL} --m-distr ${NSBHLM_MASS_DISTR} --enable-spin --min-spin1 ${NSBHLM_MIN_SPIN1} --max-spin1 ${NSBHLM_MAX_SPIN1} --min-spin2 ${NSBHLM_MIN_SPIN2} --max-spin2 ${NSBHLM_MAX_SPIN2} --gps-start-time ${START} --gps-end-time ${STOP} --dchirp-distr ${DCHIRP_DISTR} --min-distance ${MIN_DISTANCE} --max-distance ${MAX_DISTANCE} --l-distr ${L_DISTR} --i-distr ${I_DISTR} --f-lower ${FLOWER} --time-step ${TIME_STEP} --time-interval ${TIME_INTERVAL} --waveform SpinTaylorT4threePointFivePN --taper-injection startend --seed 56784 --user-tag NSBHLM4
	lalapps_inspinj --min-mass1 ${NSBHLM_MIN_MASS1} --max-mass1 ${NSBHLM_MAX_MASS1} --min-mass2 ${NSBHLM_MIN_MASS2} --max-mass2 ${NSBHLM_MAX_MASS2} --min-mtotal ${NSBHLM_MIN_MTOTAL} --max-mtotal ${NSBHLM_MAX_MTOTAL} --m-distr ${NSBHLM_MASS_DISTR} --enable-spin --min-spin1 ${NSBHLM_MIN_SPIN1} --max-spin1 ${NSBHLM_MAX_SPIN1} --min-spin2 ${NSBHLM_MIN_SPIN2} --max-spin2 ${NSBHLM_MAX_SPIN2} --gps-start-time ${START} --gps-end-time ${STOP} --dchirp-distr ${DCHIRP_DISTR} --min-distance ${MIN_DISTANCE} --max-distance ${MAX_DISTANCE} --l-distr ${L_DISTR} --i-distr ${I_DISTR} --f-lower ${FLOWER} --time-step ${TIME_STEP} --time-interval ${TIME_INTERVAL} --waveform SpinTaylorT4threePointFivePN --taper-injection startend --seed 56785 --user-tag NSBHLM5
	lalapps_inspinj --min-mass1 ${NSBHLM_MIN_MASS1} --max-mass1 ${NSBHLM_MAX_MASS1} --min-mass2 ${NSBHLM_MIN_MASS2} --max-mass2 ${NSBHLM_MAX_MASS2} --min-mtotal ${NSBHLM_MIN_MTOTAL} --max-mtotal ${NSBHLM_MAX_MTOTAL} --m-distr ${NSBHLM_MASS_DISTR} --enable-spin --min-spin1 ${NSBHLM_MIN_SPIN1} --max-spin1 ${NSBHLM_MAX_SPIN1} --min-spin2 ${NSBHLM_MIN_SPIN2} --max-spin2 ${NSBHLM_MAX_SPIN2} --gps-start-time ${START} --gps-end-time ${STOP} --dchirp-distr ${DCHIRP_DISTR} --min-distance ${MIN_DISTANCE} --max-distance ${MAX_DISTANCE} --l-distr ${L_DISTR} --i-distr ${I_DISTR} --f-lower ${FLOWER} --time-step ${TIME_STEP} --time-interval ${TIME_INTERVAL} --waveform SpinTaylorT4threePointFivePN --taper-injection startend --seed 56786 --user-tag NSBHLM6
	# NSBH HIGH MASS INJECTIONS: seeds 67891, 67892, 67893
	# Waveform: SEOBNRv2pseudoFourPN
	lalapps_inspinj --min-mass1 ${NSBHHM_MIN_MASS1} --max-mass1 ${NSBHHM_MAX_MASS1} --min-mass2 ${NSBHHM_MIN_MASS2} --max-mass2 ${NSBHHM_MAX_MASS2} --min-mtotal ${NSBHHM_MIN_MTOTAL} --max-mtotal ${NSBHHM_MAX_MTOTAL} --m-distr ${NSBHHM_MASS_DISTR} --enable-spin --aligned --min-spin1 ${NSBHHM_MIN_SPIN1} --max-spin1 ${NSBHHM_MAX_SPIN1} --min-spin2 ${NSBHHM_MIN_SPIN2} --max-spin2 ${NSBHHM_MAX_SPIN2} --gps-start-time ${START} --gps-end-time ${STOP} --dchirp-distr ${DCHIRP_DISTR} --min-distance ${MIN_DISTANCE} --max-distance ${MAX_DISTANCE} --l-distr ${L_DISTR} --i-distr ${I_DISTR} --f-lower ${FLOWER} --time-step ${TIME_STEP} --time-interval ${TIME_INTERVAL} --waveform SEOBNRv2pseudoFourPN --taper-injection start --seed 67891 --user-tag NSBHHM1
	lalapps_inspinj --min-mass1 ${NSBHHM_MIN_MASS1} --max-mass1 ${NSBHHM_MAX_MASS1} --min-mass2 ${NSBHHM_MIN_MASS2} --max-mass2 ${NSBHHM_MAX_MASS2} --min-mtotal ${NSBHHM_MIN_MTOTAL} --max-mtotal ${NSBHHM_MAX_MTOTAL} --m-distr ${NSBHHM_MASS_DISTR} --enable-spin --aligned --min-spin1 ${NSBHHM_MIN_SPIN1} --max-spin1 ${NSBHHM_MAX_SPIN1} --min-spin2 ${NSBHHM_MIN_SPIN2} --max-spin2 ${NSBHHM_MAX_SPIN2} --gps-start-time ${START} --gps-end-time ${STOP} --dchirp-distr ${DCHIRP_DISTR} --min-distance ${MIN_DISTANCE} --max-distance ${MAX_DISTANCE} --l-distr ${L_DISTR} --i-distr ${I_DISTR} --f-lower ${FLOWER} --time-step ${TIME_STEP} --time-interval ${TIME_INTERVAL} --waveform SEOBNRv2pseudoFourPN --taper-injection start --seed 67892 --user-tag NSBHHM2
	lalapps_inspinj --min-mass1 ${NSBHHM_MIN_MASS1} --max-mass1 ${NSBHHM_MAX_MASS1} --min-mass2 ${NSBHHM_MIN_MASS2} --max-mass2 ${NSBHHM_MAX_MASS2} --min-mtotal ${NSBHHM_MIN_MTOTAL} --max-mtotal ${NSBHHM_MAX_MTOTAL} --m-distr ${NSBHHM_MASS_DISTR} --enable-spin --aligned --min-spin1 ${NSBHHM_MIN_SPIN1} --max-spin1 ${NSBHHM_MAX_SPIN1} --min-spin2 ${NSBHHM_MIN_SPIN2} --max-spin2 ${NSBHHM_MAX_SPIN2} --gps-start-time ${START} --gps-end-time ${STOP} --dchirp-distr ${DCHIRP_DISTR} --min-distance ${MIN_DISTANCE} --max-distance ${MAX_DISTANCE} --l-distr ${L_DISTR} --i-distr ${I_DISTR} --f-lower ${FLOWER} --time-step ${TIME_STEP} --time-interval ${TIME_INTERVAL} --waveform SEOBNRv2pseudoFourPN --taper-injection start --seed 67893 --user-tag NSBHHM3
	# BBH INJECTIONS: seeds 78901, 78902, 78903, 78904, 78905, 78906
	# Waveform: SEOBNRv2pseudoFourPN
	lalapps_inspinj --min-mass1 ${BBH_MIN_MASS1} --max-mass1 ${BBH_MAX_MASS1} --min-mass2 ${BBH_MIN_MASS2} --max-mass2 ${BBH_MAX_MASS2} --min-mtotal ${BBH_MIN_MTOTAL} --max-mtotal ${BBH_MAX_MTOTAL} --m-distr ${BBH_MASS_DISTR} --enable-spin --aligned --min-spin1 ${BBH_MIN_SPIN1} --max-spin1 ${BBH_MAX_SPIN1} --min-spin2 ${BBH_MIN_SPIN2} --max-spin2 ${BBH_MAX_SPIN2} --gps-start-time ${START} --gps-end-time ${STOP} --dchirp-distr ${DCHIRP_DISTR} --min-distance ${MIN_DISTANCE} --max-distance ${MAX_DISTANCE} --l-distr ${L_DISTR} --i-distr ${I_DISTR} --f-lower ${FLOWER} --time-step ${TIME_STEP} --time-interval ${TIME_INTERVAL} --waveform SEOBNRv2pseudoFourPN --taper-injection start --seed 78901 --user-tag BBH1
	lalapps_inspinj --min-mass1 ${BBH_MIN_MASS1} --max-mass1 ${BBH_MAX_MASS1} --min-mass2 ${BBH_MIN_MASS2} --max-mass2 ${BBH_MAX_MASS2} --min-mtotal ${BBH_MIN_MTOTAL} --max-mtotal ${BBH_MAX_MTOTAL} --m-distr ${BBH_MASS_DISTR} --enable-spin --aligned --min-spin1 ${BBH_MIN_SPIN1} --max-spin1 ${BBH_MAX_SPIN1} --min-spin2 ${BBH_MIN_SPIN2} --max-spin2 ${BBH_MAX_SPIN2} --gps-start-time ${START} --gps-end-time ${STOP} --dchirp-distr ${DCHIRP_DISTR} --min-distance ${MIN_DISTANCE} --max-distance ${MAX_DISTANCE} --l-distr ${L_DISTR} --i-distr ${I_DISTR} --f-lower ${FLOWER} --time-step ${TIME_STEP} --time-interval ${TIME_INTERVAL} --waveform SEOBNRv2pseudoFourPN --taper-injection start --seed 78902 --user-tag BBH2
	lalapps_inspinj --min-mass1 ${BBH_MIN_MASS1} --max-mass1 ${BBH_MAX_MASS1} --min-mass2 ${BBH_MIN_MASS2} --max-mass2 ${BBH_MAX_MASS2} --min-mtotal ${BBH_MIN_MTOTAL} --max-mtotal ${BBH_MAX_MTOTAL} --m-distr ${BBH_MASS_DISTR} --enable-spin --aligned --min-spin1 ${BBH_MIN_SPIN1} --max-spin1 ${BBH_MAX_SPIN1} --min-spin2 ${BBH_MIN_SPIN2} --max-spin2 ${BBH_MAX_SPIN2} --gps-start-time ${START} --gps-end-time ${STOP} --dchirp-distr ${DCHIRP_DISTR} --min-distance ${MIN_DISTANCE} --max-distance ${MAX_DISTANCE} --l-distr ${L_DISTR} --i-distr ${I_DISTR} --f-lower ${FLOWER} --time-step ${TIME_STEP} --time-interval ${TIME_INTERVAL} --waveform SEOBNRv2pseudoFourPN --taper-injection start --seed 78903 --user-tag BBH3
	lalapps_inspinj --min-mass1 ${BBH_MIN_MASS1} --max-mass1 ${BBH_MAX_MASS1} --min-mass2 ${BBH_MIN_MASS2} --max-mass2 ${BBH_MAX_MASS2} --min-mtotal ${BBH_MIN_MTOTAL} --max-mtotal ${BBH_MAX_MTOTAL} --m-distr ${BBH_MASS_DISTR} --enable-spin --aligned --min-spin1 ${BBH_MIN_SPIN1} --max-spin1 ${BBH_MAX_SPIN1} --min-spin2 ${BBH_MIN_SPIN2} --max-spin2 ${BBH_MAX_SPIN2} --gps-start-time ${START} --gps-end-time ${STOP} --dchirp-distr ${DCHIRP_DISTR} --min-distance ${MIN_DISTANCE} --max-distance ${MAX_DISTANCE} --l-distr ${L_DISTR} --i-distr ${I_DISTR} --f-lower ${FLOWER} --time-step ${TIME_STEP} --time-interval ${TIME_INTERVAL} --waveform SEOBNRv2pseudoFourPN --taper-injection start --seed 78904 --user-tag BBH4
	lalapps_inspinj --min-mass1 ${BBH_MIN_MASS1} --max-mass1 ${BBH_MAX_MASS1} --min-mass2 ${BBH_MIN_MASS2} --max-mass2 ${BBH_MAX_MASS2} --min-mtotal ${BBH_MIN_MTOTAL} --max-mtotal ${BBH_MAX_MTOTAL} --m-distr ${BBH_MASS_DISTR} --enable-spin --aligned --min-spin1 ${BBH_MIN_SPIN1} --max-spin1 ${BBH_MAX_SPIN1} --min-spin2 ${BBH_MIN_SPIN2} --max-spin2 ${BBH_MAX_SPIN2} --gps-start-time ${START} --gps-end-time ${STOP} --dchirp-distr ${DCHIRP_DISTR} --min-distance ${MIN_DISTANCE} --max-distance ${MAX_DISTANCE} --l-distr ${L_DISTR} --i-distr ${I_DISTR} --f-lower ${FLOWER} --time-step ${TIME_STEP} --time-interval ${TIME_INTERVAL} --waveform SEOBNRv2pseudoFourPN --taper-injection start --seed 78905 --user-tag BBH5
	lalapps_inspinj --min-mass1 ${BBH_MIN_MASS1} --max-mass1 ${BBH_MAX_MASS1} --min-mass2 ${BBH_MIN_MASS2} --max-mass2 ${BBH_MAX_MASS2} --min-mtotal ${BBH_MIN_MTOTAL} --max-mtotal ${BBH_MAX_MTOTAL} --m-distr ${BBH_MASS_DISTR} --enable-spin --aligned --min-spin1 ${BBH_MIN_SPIN1} --max-spin1 ${BBH_MAX_SPIN1} --min-spin2 ${BBH_MIN_SPIN2} --max-spin2 ${BBH_MAX_SPIN2} --gps-start-time ${START} --gps-end-time ${STOP} --dchirp-distr ${DCHIRP_DISTR} --min-distance ${MIN_DISTANCE} --max-distance ${MAX_DISTANCE} --l-distr ${L_DISTR} --i-distr ${I_DISTR} --f-lower ${FLOWER} --time-step ${TIME_STEP} --time-interval ${TIME_INTERVAL} --waveform SEOBNRv2pseudoFourPN --taper-injection start --seed 78906 --user-tag BBH6
